"""add bullwhip records

Revision ID: 4cae8ba75a20
Revises: 83c2d4e5f601
Create Date: 2026-09-05 21:13:13.244296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cae8ba75a20'
down_revision: Union[str, Sequence[str], None] = '83c2d4e5f601'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bullwhip_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('customer_demand', sa.Float(), nullable=False),
    sa.Column('retailer_orders', sa.Float(), nullable=False),
    sa.Column('distributor_orders', sa.Float(), nullable=False),
    sa.Column('manufacturer_orders', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'date', name='uq_bullwhip_org_date')
    )
    op.create_index(op.f('ix_bullwhip_records_date'), 'bullwhip_records', ['date'], unique=False)
    op.create_index(op.f('ix_bullwhip_records_organization_id'), 'bullwhip_records', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bullwhip_records_organization_id'), table_name='bullwhip_records')
    op.drop_index(op.f('ix_bullwhip_records_date'), table_name='bullwhip_records')
    op.drop_table('bullwhip_records')
    # ### end Alembic commands ###
